apiVersion: apps/v1
kind: Deployment
metadata:
 name: auth-srv
 namespace: optimus-demo
 labels:
  app: authsrv
spec:
 selector:
  matchLabels:
   app: authsrv
 replicas: 1
 template:
  metadata:
   labels:
    app: authsrv
  spec:
   volumes:
    - name: auth-srv-config-volume
      configMap:
        name: auth-srv-config
        items:
        - key: application.yml
          path: application.yml
    - name: optimus-auth-server
      hostPath:
       path: /opt/optimus/auth_srv
    - name: optimus-auth-logs
      hostPath:
       path: /var/log/optimus/auth_srv
    - name: tmp
      emptyDir: {}
   serviceAccountName: ""
   automountServiceAccountToken: false  
   containers:
    - name: auth-server
      image: optimusacr01.azurecr.io/auth-server:3.1.0
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 0.2
          memory: 0.5G
        requests:
          cpu: 0.2
          memory: 0.5G
      securityContext:
        privileged: false
        runAsUser: 2000
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
      env:
       - name: mongodb.cosmos.host
         valueFrom:
          configMapKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.host
       - name: mongodb.cosmos.port
         valueFrom:
          configMapKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.port
       - name: azurejwks-url
         valueFrom:
          configMapKeyRef:
           name: optimus
           key: azurejwks-url
       - name: mongodb.cosmos.username
         valueFrom:
          secretKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.username
       - name: mongodb.cosmos.password
         valueFrom:
          secretKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.password
       - name: jwt.secretKey
         valueFrom:
          secretKeyRef:
           name: token
           key: jwt.secretKey
       - name: refToken.key
         valueFrom:
          secretKeyRef:
           name: token
           key: refToken.key
       - name: clientSecrets.aciworldwide
         valueFrom:
          secretKeyRef:
           name: token
           key: clientSecrets.aciworldwide
       - name: clientSecrets.adidas-aciworldwide
         valueFrom:
          secretKeyRef:
           name: token
           key: clientSecrets.adidas-aciworldwide
      volumeMounts:
       - name: auth-srv-config-volume
         mountPath: /tmp/conf
       - name: optimus-auth-server
         mountPath: /opt/optimus/auth_srv
       - name: optimus-auth-logs
         mountPath: /var/log/optimus
       - name: tmp
         mountPath: /tmp
      ports:
       - containerPort: 9090
   nodeSelector:
     optimusnode: eksnode03uat


---


apiVersion: v1
kind: Service
metadata:
   name: auth-service
   namespace: optimus-demo
   labels:
    app: authsrv
spec:
   selector:
    app: authsrv
   ports:
    - protocol: TCP
      port: 80
      targetPort: 9090

