
apiVersion: apps/v1
kind: Deployment
metadata:
 name: casemgmt-srv
 namespace: optimus-demo
 labels:
  app: casemgmt-srv
spec:
 selector:
  matchLabels:
   app: casemgmt-srv
 replicas: 1
 revisionHistoryLimit: 5
 template:
  metadata:
   labels:
    app: casemgmt-srv
  spec:
   volumes:
    - name: casemgmt-srv-config-volume
      configMap:
        name: casemgmt-srv-config
        items:
        - key: application.yml
          path: application.yml
    - name: optimus-casemgmt-server
      hostPath:
       path: /opt/optimus/casemgmt_srv
    - name: optimus-casemgmt-logs
      hostPath:
       path: /var/log/optimus/casemgmt-srv
    - name: tmp
      emptyDir: {}
   serviceAccountName: ""
   automountServiceAccountToken: false  
   containers:
    - name: casemgmt-server
      image: optimusacr01.azurecr.io/case-management-server:3.1.0
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 0.2
          memory: 0.5G
        requests:
          cpu: 0.2
          memory: 0.2G
      securityContext:
        privileged: false
        runAsUser: 2000
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
      env:
       - name: mongodb.cosmos.host
         valueFrom:
          configMapKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.host
       - name: mongodb.cosmos.port
         valueFrom:
          configMapKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.port
       - name: azurejwks-url
         valueFrom:
          configMapKeyRef:
           name: optimus
           key: azurejwks-url
       - name: mongodb.cosmos.username
         valueFrom:
          secretKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.username
       - name: mongodb.cosmos.password
         valueFrom:
          secretKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.password
       - name: jwt.secretKey
         valueFrom:
          secretKeyRef:
           name: token
           key: jwt.secretKey
       - name: refToken.key
         valueFrom:
          secretKeyRef:
           name: token
           key: refToken.key
      volumeMounts:
       - name: casemgmt-srv-config-volume
         mountPath: /tmp/conf
       - name: optimus-casemgmt-server
         mountPath: /opt/optimus/casemgmt_srv
       - name: optimus-casemgmt-logs
         mountPath: /var/log/optimus
       - name: tmp
         mountPath: /tmp
      ports:
       - containerPort: 8283
   nodeSelector:
     optimusnode: eksnode02uat

---

apiVersion: v1
kind: Service
metadata:
   name: casemgmt-service
   namespace: optimus-demo
   labels:
    app: casemgmt-srv
spec:
   selector:
    app: casemgmt-srv
   ports:
    - protocol: TCP
      port: 80
      targetPort: 8283

