apiVersion: v1
kind: ConfigMap
metadata:
  name: casemgmt-srv-config
  namespace: optimus-demo
  labels:
    app: casemgmt-srv
data:
  application.yml: |+

    logging:
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } --- [%t] %-40.40logger{39} : %X{RID} %X{CID} - %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}"
        level: debug
      file.path: /var/log/optimus
    server:
      address: 0.0.0.0
      port: 8283
      servlet:
        context-path: /case
      tomcat:
        accesslog:
          enabled: true
          prefix: access-log
          suffix: .log
          pattern: '%h %{X-Forwarded-For}i %t %r %s %b %D %p'

    userContextGenerator:
      exclude:
        urlPatterns: /batch/**,/issues,/issue/**,/casetemplate/internal/**

    jwt:
      secretKey: ${jwt.secretKey}
      notAfterInMins: 30
      expiryInMins: 15

    azure:
      jwksUrl: ${azurejwks-url}

    refToken:
        key: ${refToken.key}
        iV: 1234567890ABCDEF

    authToken:
        key: ${refToken.key}
        iV: 1234567890ABCDEF

    ##

    spring:
      main.allow-circular-references: true
      mvc:
        pathmatch:
          matching-strategy: ant_path_matcher
      data:
        mongodb:
          uri: mongodb+srv://${mongodb.cosmos.username}:${mongodb.cosmos.password}@${mongodb.cosmos.host}/default?ssl=true&authSource=admin      
      autoconfigure:
        exclude:
          - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
          - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

    optimus:
      rest:
        swagger: true

    pattern:
      name: '[a-zA-Z0-9-_]+'

    batch:
      record:
        limit: 50

    processing:
      wait:
        time:
          insec: 86400

    retry:
      after:
        time:
          insec: 5
      max:
        count: 1

    multi-tenant:
      enabled: true
      repositoryBasePackage: com.opus.optimus
      common:
        dbConnection:
          uri: mongodb+srv://${mongodb.cosmos.username}:${mongodb.cosmos.password}@${mongodb.cosmos.host}/common?ssl=true&authSource=admin
      tenants:
        dbConnections:
          optimus:
            uri: mongodb+srv://${mongodb.cosmos.username}:${mongodb.cosmos.password}@${mongodb.cosmos.host}/optimus?ssl=true&authSource=admin
          aci:
            uri: mongodb+srv://${mongodb.cosmos.username}:${mongodb.cosmos.password}@${mongodb.cosmos.host}/aci?ssl=true&authSource=admin
          optimusfin:
            uri: mongodb+srv://${mongodb.cosmos.username}:${mongodb.cosmos.password}@${mongodb.cosmos.host}/optimusfin?ssl=true&authSource=admin
          optimusops:
            uri: mongodb+srv://${mongodb.cosmos.username}:${mongodb.cosmos.password}@${mongodb.cosmos.host}/optimusops?ssl=true&authSource=admin
          aciworldwide:
            uri: mongodb+srv://${mongodb.cosmos.username}:${mongodb.cosmos.password}@${mongodb.cosmos.host}/aciworldwide?ssl=true&authSource=admin
          adidas-aciworldwide:
            uri: mongodb+srv://${mongodb.cosmos.username}:${mongodb.cosmos.password}@${mongodb.cosmos.host}/adidas-aciworldwide?ssl=true&authSource=admin

    case.processing.disabled: paysafe,paysafeops,optimus,galileo,godaddy

    case:
      batchSize: 1024
      sourceACaseWaitDays: 25
      sourceBCaseWaitDays: 25

