
apiVersion: apps/v1
kind: Deployment
metadata:
 name: audit-srv
 namespace: optimus-demo
 labels:
  app: audit-srv
spec:
 selector:
  matchLabels:
   app: audit-srv
 replicas: 1
 revisionHistoryLimit: 5
 template:
  metadata:
   labels:
    app: audit-srv
  spec:
   volumes:
    - name: audit-srv-config-volume
      configMap:
        name: audit-srv-config
        items:
        - key: application.yml
          path: application.yml
    - name: optimus-audit-server
      hostPath:
       path: /opt/optimus/audit_srv
    - name: optimus-audit-logs
      hostPath:
       path: /var/log/optimus/audit-srv
    - name: tmp
      emptyDir: {}
   serviceAccountName: ""
   automountServiceAccountToken: false  
   containers:
    - name: audit-server
      image: optimusacr01.azurecr.io/audit-server:3.1.0
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 0.2
          memory: 0.5G
        requests:
          cpu: 0.2
          memory: 0.2G
      securityContext:
        privileged: false
        runAsUser: 2000
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
      env:
       - name: mongodb.cosmos.host
         valueFrom:
          configMapKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.host
       - name: mongodb.cosmos.port
         valueFrom:
          configMapKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.port
       - name: azurejwks-url
         valueFrom:
          configMapKeyRef:
           name: optimus
           key: azurejwks-url
       - name: mongodb.cosmos.username
         valueFrom:
          secretKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.username
       - name: mongodb.cosmos.password
         valueFrom:
          secretKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.password
       - name: jwt.secretKey
         valueFrom:
          secretKeyRef:
           name: token
           key: jwt.secretKey
       - name: refToken.key
         valueFrom:
          secretKeyRef:
           name: token
           key: refToken.key
      volumeMounts:
       - name: audit-srv-config-volume
         mountPath: /tmp/conf
       - name: optimus-audit-server
         mountPath: /opt/optimus/audit_srv
       - name: optimus-audit-logs
         mountPath: /var/log/optimus
       - name: tmp
         mountPath: /tmp
      ports:
       - containerPort: 8287
   nodeSelector:
     optimusnode: eksnode03uat

---

apiVersion: v1
kind: Service
metadata:
   name: audit-service
   namespace: optimus-demo
   labels:
    app: audit-srv
spec:
   selector:
    app: audit-srv
   ports:
    - protocol: TCP
      port: 80
      targetPort: 8287

