apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-internal-lb
  namespace: optimus-demo
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - name: rest
    port: 8081
    targetPort: 8081
  selector:
    app: flink
    component: jobmanager
