
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-srv-config
  namespace: optimus-demo
  labels:
    app: nginx
data:
  default.conf: |+

    server {
        listen       443 ssl http2 default_server;
        listen       [::]:443 ssl http2 default_server;
        server_name  _;

        ssl_certificate "/opts3/optimus-share/certs/k8fake.crt";
        ssl_certificate_key "/opts3/optimus-share/certs/k8fake.key";

        location / {
          proxy_pass http://172.29.0.8;
        }

        location /auth {
          proxy_pass http://172.29.0.188;
        }

        location /config/ {
          proxy_pass http://172.29.0.37;
        }

        location /report-server {
          proxy_pass http://report-service;
        }

        location /scheduler-server {
          proxy_pass http://scheduler-service;
        }

        location /taskmanager {
          proxy_pass http://taskmanager-service;
        }
        location /admin-server {
          proxy_pass http://172.29.0.187;
        }

        location /audit-server {
          proxy_pass http://audit-service;
        }

        location /case {
          proxy_pass http://casemgmt-service;
          proxy_set_header content-type "application/json";
        }
        
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
          root   /usr/share/nginx/html;
        }
    }
