
apiVersion: v1
kind: Service
metadata:
  name: nginx-server
  namespace: optimus-demo
spec:
  ports:
  - name: rest
    port: 443
    targetPort: 80
  selector:
    app: nginx
    component: nginx-server
