apiVersion: v1
kind: Service
metadata:
  name: nginx-internal-lb
  namespace: optimus-demo
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - name: rest
    port: 80
    targetPort: 80
  selector:
    app: nginx
    component: nginx-server
