apiVersion: apps/v1
kind: Deployment
metadata:
 name: optimus-ui-service
 namespace: optimus-demo
 labels:
  app: optimus-ui-service
spec:
 selector:
  matchLabels:
   app: optimus-ui-service
 replicas: 1
 revisionHistoryLimit: 5
 template:
  metadata:
   labels:
    app: optimus-ui-service
  spec:
   volumes:
    - name: optimus-ui-server
      hostPath:
       path: /opt/optimus/admin_srv
    - name: optimus-ui-logs
      hostPath:
       path: /var/log/optimus/optimus-ui-service
    - name: tmp
      emptyDir: {}
   serviceAccountName: ""
   automountServiceAccountToken: false
   containers:
    - name: optimus-ui-server
      image: optimusacr01.azurecr.io/optimus-ui:3.1.0
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 0.2
          memory: 0.5G
        requests:
          cpu: 0.2
          memory: 0.2G
      securityContext:
        privileged: false
        runAsUser: 2000
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
      env:
       - name: DATABASE_URI
         valueFrom:
          secretKeyRef:
           name: mongodbcosmos
           key: DATABASE_URI
      volumeMounts:
       - name: optimus-ui-server
         mountPath: /opt/optimus/admin_srv
       - name: optimus-ui-logs
         mountPath: /var/log/optimus/optimus-ui-service
       - name: tmp
         mountPath: /tmp
      ports:
       - containerPort: 4000
   nodeSelector:
     optimusnode: eksnode03uat

---

apiVersion: v1
kind: Service
metadata:
   name: optimus-ui-services
   namespace: optimus-demo
   labels:
    app: optimus-ui-service
spec:
   selector:
    app: optimus-ui-service
   ports:
    - protocol: TCP
      port: 80
      targetPort: 4000

