apiVersion: apps/v1
kind: Deployment
metadata:
 name: taskmanager
 namespace: optimus-demo
 labels:
  app: taskmanager
spec:
 selector:
  matchLabels:
   app: taskmanager
 replicas: 1
 template:
  metadata:
   labels:
    app: taskmanager
  spec:
   volumes:
    - name: taskmanager-volume
      configMap:
        name: taskmanager-config
        items:
        - key: application.yml
          path: application.yml
    - name: optimus-taskmanager
      hostPath:
       path: /opt/optimus/taskmanager_srv
    - name: optimus-taskmanager-logs
      hostPath:
       path: /var/log/optimus/taskmanager-srv
    - name: tmp
      emptyDir: {}
   serviceAccountName: ""
   automountServiceAccountToken: false  
   containers:
    - name: taskmanager-server
      image: optimusacr01.azurecr.io/task-manager-server:3.1.0
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 0.2
          memory: 0.5G
        requests:
          cpu: 0.2
          memory: 0.2G
      securityContext:
        privileged: false
        runAsUser: 2000
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
      env:
       - name: mongodb.cosmos.host
         valueFrom:
          configMapKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.host
       - name: mongodb.cosmos.port
         valueFrom:
          configMapKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.port
       - name: azurejwks-url
         valueFrom:
          configMapKeyRef:
           name: optimus
           key: azurejwks-url
       - name: mongodb.cosmos.username
         valueFrom:
          secretKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.username
       - name: mongodb.cosmos.password
         valueFrom:
          secretKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.password
       - name: jwt.secretKey
         valueFrom:
          secretKeyRef:
           name: token
           key: jwt.secretKey
       - name: refToken.key
         valueFrom:
          secretKeyRef:
           name: token
           key: refToken.key
      volumeMounts:
       - name: taskmanager-volume
         mountPath: /tmp/conf
       - name: optimus-taskmanager
         mountPath: /opt/optimus
       - name: optimus-taskmanager-logs
         mountPath: /var/log/optimus
       - name: tmp
         mountPath: /tmp
      ports:
       - containerPort: 8286
   nodeSelector:
     optimusnode: eksnode02uat


---

apiVersion: v1
kind: Service
metadata:
   name: taskmanager-service
   namespace: optimus-demo
   labels:
    app: taskmanager
spec:
   selector:
    app: taskmanager
   ports:
    - protocol: TCP
      port: 80
      targetPort: 8286

